### ISSUE TITLE
Feature #3 Sessions Tracking Workflow (Front-End)

### ISSUE THREAD

**Issue by waltonzt** [jordangaston/capstone-zack-jordan#12]
- [x] User needs to be able to start a new sessions. 
- [x] Time stamp of start and end date
- [x] Store user session notes
- [x] Track the sessions with a timer either count up. 
- [x] End Session/Store Data in a Session Object
- [x] Track user Id
- [x] Store in Database
- [x] See data on dashboard

**Comment by waltonzt** [comment]
@jordangaston This is ready for backend Integration
